version: '3.8'
services:
  devcontainer:
    image: 'node-18-custom'
    build: '.'
    command: sleep infinity
    environment:
      - ORFARCHIV_DB_URL=mongodb://orfarchiv-db
    ports:
      - '3001:3001'
      - '3301:3301'
      - '6006:6006'
    networks:
      - orfarchiv-dev-network
    volumes:
      - ../..:/workspaces:cached
  orfarchiv-db:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - orfarchiv-dev-network
    volumes:
      - orfarchiv-dev:/data/db
    restart: unless-stopped
  orfarchiv-db-ui:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=orfarchiv-db
    ports:
      - '3002:8081'
    networks:
      - orfarchiv-dev-network
    restart: unless-stopped
networks:
  orfarchiv-dev-network:
volumes:
  orfarchiv-dev:
